(letrec
    (COMPILE (quote 
        (ADD (SUB x y) 2) # компилируемая программа (Внимание! Не проверяется синтаксически.)
    ))
    (COMPILE (
        lambda (E) (
            COMP E (quote ((x y))) (quote Nil) # тестовое окружение ((x y))
        )
    ))
    (COMP (
        lambda (E N C)
            (cond (LITERAL E)
                (CONS (QUOTE LDC) (CONS E C))
            (cond (ATOM E) # символьный атом, т.к. не литерал
                (CONS (QUOTE LD) (CONS (LOCATION E N) C))
            (cond (EQUAL (CAR E) (QUOTE QUOTE))
                (CONS (QUOTE LDC) (CONS (CAR (CDR E)) C))
            (cond (EQUAL (CAR E) (QUOTE ADD))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE ADD) C)))
            (cond (EQUAL (CAR E) (QUOTE SUB))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE SUB) C)))
            (cond (EQUAL (CAR E) (QUOTE MUL))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE MUL) C)))
            (cond (EQUAL (CAR E) (QUOTE DIVE))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE DIVE) C)))
            (cond (EQUAL (CAR E) (QUOTE REM))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE REM) C)))
            (cond (EQUAL (CAR E) (QUOTE LE))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE LE) C)))
            (cond (EQUAL (CAR E) (QUOTE EQUAL))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE EQUAL) C)))
            (cond (EQUAL (CAR E) (QUOTE CAR))
                (COMP (CAR (CDR E)) N (CONS (QUOTE CAR) C))
            (cond (EQUAL (CAR E) (QUOTE CDR))
                (COMP (CAR (CDR E)) N (CONS (QUOTE CDR) C))
            (cond (EQUAL (CAR E) (QUOTE ATOM))
                (COMP (CAR (CDR E)) N (CONS (QUOTE ATOM) C))
            (cond (EQUAL (CAR E) (QUOTE CONS))
                (COMP (CAR (CDR (CDR E))) N (COMP (CAR (CDR E)) N (CONS (QUOTE CONS) C)))
                (QUOTE -12345)
        ))))))))))))))
    ))
    (LOCATION (LAMBDA (E1 N1)
        (LETREC
            (cond (MEMBER E1 (CAR N1)) 
                (CONS (QUOTE 0) (CONS (POSN E1 (CAR N1)) NIL)) 
                (INCAR (LOCATION E1 (CDR N1)))
            )
            
            (MEMBER (LAMBDA (E N)
                (cond (EQUAL N (QUOTE NIL)) (quote FALSE)
                (cond (EQUAL E (CAR N)) (quote TRUE) (MEMBER E (CDR N))))))
            (POSN (LAMBDA (E N)
                (cond (EQUAL E (CAR N)) (QUOTE 0) (ADD (QUOTE 1) (POSN E (CDR N))))))
            (INCAR (LAMBDA (L) (CONS (ADD (QUOTE 1) (CAR L)) (CDR L))))
        ))
    )
)