(LETREC
    (COMPILE (QUOTE 
        (LAMBDA (a b) (add a 2)) # компилируемая программа (Внимание! Не проверяется синтаксически и семантически.)
    ))

    (COMPILE (LAMBDA (E) (
            COMP E (QUOTE ((x y))) (QUOTE Nil) # тестовое окружение ((x y))
        )
    ))
    (COMP (LAMBDA (E N C)
            (COND (LITERAL E)
                (CONS (QUOTE LDC) (CONS E C))
            (COND (ATOM E) # символьный атом, т.к. не литерал
                (CONS (QUOTE LD) (CONS (LOCATION E N) C))
            (COND (EQUAL (CAR E) (QUOTE QUOTE))
                (CONS (QUOTE LDC) (CONS (CAR (CDR E)) C))
            (COND (EQUAL (CAR E) (QUOTE ADD))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE ADD) C)))
            (COND (EQUAL (CAR E) (QUOTE SUB))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE SUB) C)))
            (COND (EQUAL (CAR E) (QUOTE MUL))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE MUL) C)))
            (COND (EQUAL (CAR E) (QUOTE DIVE))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE DIVE) C)))
            (COND (EQUAL (CAR E) (QUOTE REM))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE REM) C)))
            (COND (EQUAL (CAR E) (QUOTE LE))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE LE) C)))
            (COND (EQUAL (CAR E) (QUOTE EQUAL))
                (COMP (CAR (CDR E)) N (COMP (CAR (CDR (CDR E))) N (CONS (QUOTE EQUAL) C)))
            (COND (EQUAL (CAR E) (QUOTE CAR))
                (COMP (CAR (CDR E)) N (CONS (QUOTE CAR) C))
            (COND (EQUAL (CAR E) (QUOTE CDR))
                (COMP (CAR (CDR E)) N (CONS (QUOTE CDR) C))
            (COND (EQUAL (CAR E) (QUOTE ATOM))
                (COMP (CAR (CDR E)) N (CONS (QUOTE ATOM) C))
            (COND (EQUAL (CAR E) (QUOTE CONS))
                (COMP (CAR (CDR (CDR E))) N (COMP (CAR (CDR E)) N (CONS (QUOTE CONS) C)))
            (COND (EQUAL (CAR E) (QUOTE COND))
                (LET (COMP (CAR (CDR E)) N (CONS (QUOTE SEL) (CONS THENPT (CONS ELSEPT C))))
                (THENPT (COMP (CAR (CDR (CDR E))) N (QUOTE (JOIN))))
                (ELSEPT (COMP (CAR (CDR (CDR (CDR E)))) N (QUOTE (JOIN)))))
            (cond (EQUAL (CAR E) (QUOTE LAMBDA))
                (LET (CONS (QUOTE LDF) (CONS BODY C))
                    (BODY (COMP (CAR (CDR (CDR E))) (CONS (CAR (CDR E)) N) (QUOTE (RTN)))))
            (QUOTE -12345)
        ))))))))))))))))
    ))
    (LOCATION (LAMBDA (E1 N1)
        (LETREC
            (cond (MEMBER E1 (CAR N1)) 
                (CONS (QUOTE 0) (CONS (POSN E1 (CAR N1)) NIL)) 
                (INCAR (LOCATION E1 (CDR N1)))
            )
            
            (MEMBER (LAMBDA (E N)
                (cond (EQUAL N (QUOTE NIL)) (quote FALSE)
                (cond (EQUAL E (CAR N)) (quote TRUE) (MEMBER E (CDR N))))))
            (POSN (LAMBDA (E N)
                (cond (EQUAL E (CAR N)) (QUOTE 0) (ADD (QUOTE 1) (POSN E (CDR N))))))
            (INCAR (LAMBDA (L) 
                (CONS (ADD (QUOTE 1) (CAR L)) (CDR L))))
        ))
    )
)